version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    # Add default Kodiak `merge.automerge_label`
    - "automerge"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: exports-loader
    versions:
    - "> 0.7.0"
